// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: proto2.proto

package testproto

import (
	proto "github.com/RomiChan/protobuf/proto"
)

type Proto2 struct {
	BoolValue  proto.Option[bool]    `protobuf:"varint,1,opt"`
	Int32Val   proto.Option[int32]   `protobuf:"varint,2,opt"`
	Uint32Val  proto.Option[uint32]  `protobuf:"varint,3,opt"`
	Int64Val   proto.Option[int64]   `protobuf:"varint,4,opt"`
	Uint64Val  proto.Option[uint64]  `protobuf:"varint,5,opt"`
	FloatVal   proto.Option[float32] `protobuf:"fixed32,6,opt"`
	DoubleVal  proto.Option[float64] `protobuf:"fixed64,7,opt"`
	StringVal  proto.Option[string]  `protobuf:"bytes,8,opt"`
	BytesVal   []byte                `protobuf:"bytes,9,opt"`
	Fixed32Val proto.Option[uint32]  `protobuf:"fixed32,10,opt"`
	Fixed64Val proto.Option[uint64]  `protobuf:"fixed64,11,opt"`
	Sint32Val  proto.Option[int32]   `protobuf:"zigzag32,12,opt"`
	Sint64Val  proto.Option[int64]   `protobuf:"zigzag64,13,opt"`
	Nested     *Proto2_NestedMessage `protobuf:"bytes,14,opt"`
}

type Proto2_NestedMessage struct {
	Int32Val  proto.Option[int32]  `protobuf:"varint,1,opt"`
	Int64Val  proto.Option[int64]  `protobuf:"varint,2,opt"`
	StringVal proto.Option[string] `protobuf:"bytes,3,opt"`
}
